<?php
/**
 * This file is part of the PokeMe Application.
 *
 * PHP version 5
 *
 * (c) Alexandre Tranchant <alexandre.tranchant@gmail.com>
 *
 * @category ModelManager
 *
 * @author    Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @copyright 2015 Alexandre Tranchant
 * @license   GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */
namespace AppBundle\Tests;

use AppBundle\Entity\Annuaire;
use AppBundle\Entity\Validation;
use AppBundle\Model\AnnuaireManager;
use Application\Sonata\UserBundle\Entity\User;

/**
 * Entity Annuaire Class Tests.
 * Skeleton generated by PHPUnit_SkeletonGenerator.
 *
 * @category Testing
 *
 * @author  Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @license GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */
class AnnuaireManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Doctrine Entity Manager (Mock).
     *
     * @var \PHPUnit_Framework_MockObject_MockObject
     */
    private $entityManager;

    /**
     * Repository Entity (Mock).
     *
     * @var \PHPUnit_Framework_MockObject_MockObject
     */
    private $repository;

    /**
     * Annuaire Manager to test.
     *
     * @var AnnuaireManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->repository = $this->getMockBuilder('Doctrine\Orm\EntityRepository')
            ->disableOriginalConstructor()
            ->getMock();
        $this->entityManager = $this->getMockBuilder('Doctrine\ORM\EntityManager')
            ->disableOriginalConstructor()
            ->getMock();
        $this->entityManager->expects($this->exactly(1))
            ->method('getRepository')
            ->willReturn($this->repository);
        $this->object = new AnnuaireManager($this->entityManager, 'AppBundle\Entity\Annuaire');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->entityManager = null;
        $this->object = null;
        parent::tearDown();
    }

    /**
     * Test constructor.
     *
     * @covers AppBundle\Model\AnnuaireManager::__construct()
     */
    public function testConstruct()
    {
        $this->assertEquals($this->entityManager, \PHPUnit_Framework_Assert::readAttribute($this->object, 'objectManager'));
        $this->assertEquals($this->repository, \PHPUnit_Framework_Assert::readAttribute($this->object, 'repository'));
    }
    /**
     * Test Creation of an Annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::createAnnuaire
     */
    public function testCreateAnnuaire()
    {
        $expected = new Annuaire();
        $annuaire = $this->object->createAnnuaire();
        $this->assertEquals($expected, $annuaire);
    }

    /**
     * Test deletion of an annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::deleteAnnuaire
     */
    public function testDeleteAnnuaire()
    {
        $this->entityManager->expects($this->exactly(1))
            ->method('remove');
        $this->entityManager->expects($this->exactly(1))
            ->method('flush');
        $annuaire = new Annuaire();
        $this->object->deleteAnnuaire($annuaire);
    }

    /**
     * Test validation of an annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::validateAnnuaire
     */
    public function testValidateAnnuaire()
    {
        $user = new User();
        $annuaire = $this->object->createAnnuaire();
        $expected = new Validation();
        $expected->setValidator($user);
        $expected->setStatus(Validation::ACCEPTE);
        $this->object->validateAnnuaire($annuaire, $user);
        $this->assertEquals($expected, $annuaire->getValidation());
        $expected->setReason('foo');
        $this->object->validateAnnuaire($annuaire, $user, 'foo');
        $this->assertEquals($expected, $annuaire->getValidation());
    }

    /**
     * Test reject of an annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::rejectAnnuaire
     */
    public function testRejectAnnuaire()
    {
        $user = new User();
        $annuaire = $this->object->createAnnuaire();
        $expected = new Validation();
        $expected->setValidator($user);
        $expected->setStatus(Validation::REFUSE);
        $this->object->rejectAnnuaire($annuaire, $user);
        $this->assertEquals($expected, $annuaire->getValidation());
        $expected->setReason('foo');
        $this->object->rejectAnnuaire($annuaire, $user, 'foo');
        $this->assertEquals($expected, $annuaire->getValidation());
    }

    /**
     * Test stay Waiting of an annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::stayWaitingAnnuaire
     */
    public function testStayWaitingAnnuaire()
    {
        $user = new User();
        $annuaire = $this->object->createAnnuaire();
        $expected = new Validation();
        $expected->setValidator($user);
        $expected->setStatus(Validation::EN_ATTENTE);
        $this->object->stayWaitingAnnuaire($annuaire, $user);
        $this->assertEquals($expected, $annuaire->getValidation());
        $expected->setReason('foo');
        $this->object->stayWaitingAnnuaire($annuaire, $user, 'foo');
        $this->assertEquals($expected, $annuaire->getValidation());
    }

    /**
     * Test reload|reset of an annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::reloadAnnuaire
     */
    public function testReloadAnnuaire()
    {
        $this->entityManager->expects($this->exactly(1))
            ->method('refresh');
        $annuaire = new Annuaire();
        $this->object->reloadAnnuaire($annuaire);
    }

    /**
     * Test persistence update of an annuaire.
     *
     * @covers AppBundle\Model\AnnuaireManager::updateAnnuaire
     */
    public function testUpdateAnnuaire()
    {
        $annuaire = new Annuaire();
        $this->entityManager->expects($this->exactly(6))
            ->method('persist');
        $this->entityManager->expects($this->exactly(2))
            ->method('flush');
        $this->object->updateAnnuaire($annuaire, false);
        $this->object->updateAnnuaire($annuaire, true);
        $this->object->updateAnnuaire($annuaire);
    }
}
