language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'create database pokeme;'
  - composer self-update
  - composer install --no-interaction --prefer-source
  - php app/console doctrine:migrations:migrate  --no-interaction
  - php app/console doctrine:fixtures:load -n --env=test
  - php app/console fos:user:create testuser test@example.com secret
  - php app/console fos:user:create inactiveuser inactive@example.com secret --inactive
  - php app/console fos:user:create admin admin@example.com secret --super-admin
  - mkdir -p build/logs
  - chmod -R 0777 web/uploads
script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit -c app/ --coverage-clover build/logs/clover.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then phpunit -c app/ ; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls --no-interaction --prefer-source; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php bin/coveralls -v; fi

notifications:
  email:
    - alexandre.tranchant@gmail.com
