build: false
platform: x86
clone_folder: c:\projects\alexandre-t\pokeme

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.6\bin;C:\Program Files\OpenSSL;c:\tools\php;%PATH%

services:
  - mysql

#environment:
#  matrix:
#    - COMPOSER_FLAGS: ""
#    - COMPOSER_FLAGS: --prefer-lowest --prefer-stable

install:
  #Database Creation
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cd c:\tools\php
  #PHP installation
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo memory_limit=1G >> php.ini

test_script:
  #Service Mysql is now running
  - mysql -e "create database pokeme;" --user=root -p"Password12!"
  #build application
  - cd %APPVEYOR_BUILD_FOLDER%
  - copy app\config\parameters.yml.appveyor app\config\parameters.yml
  - php -r "readfile('http://getcomposer.org/installer');" | php
#  - php composer.phar update %COMPOSER_FLAGS% --prefer-source --no-interaction --no-progress
  - php composer.phar update --prefer-source --no-interaction --no-progress
  - appveyor DownloadFile https://phar.phpunit.de/phpunit.phar
  - php app/console doctrine:migrations:migrate  --no-interaction
  - php app/console doctrine:fixtures:load -n --env=test
  - php app/console fos:user:create testuser test@example.com secret
  - php app/console fos:user:create inactiveuser inactive@example.com secret --inactive
  - php app/console fos:user:create admin admin@example.com secret --super-admin
#launch tests
  - cd c:\projects\alexandre-t\pokeme
  - php phpunit.phar -c app --verbose

