# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    app.example:
#        class: %app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    app.annuaire_manager:
        class: AppBundle\Model\AnnuaireManager
        arguments: [@doctrine.orm.entity_manager, 'AppBundle\Entity\Annuaire']
