Application\Sonata\MediaBundle\Entity\Gallery:
  type: entity
  repositoryClass: Doctrine\ORM\EntityRepository
  table: te_gallery_gal
  id:
    id:
      type: integer
      column: id
      generator:
        strategy: AUTO
