AppBundle\Entity\Annuaire:
  type: entity
  table: te_annuaire_ann
  id:
    id:
      type: integer
      column: ann_id
      generator:
        strategy: AUTO
      options:
        unsigned: true
        comment: Identifiant de l annuaire
  fields:
    name:
      type: string
      length: 64
      nullable: false
      column: ann_libelle
      options:
        comment: Nom de l annuaire
    description:
      type: text
      length: 16777215
      nullable: true
      column: ann_description
      options:
        comment: Description de l annuaire
    url:
      type: string
      length: 255
      nullable: true
      column: ann_url
      options:
        comment: Url officiel du site diffusant l annuaire
    created:
      type: datetime
      nullable: false
      column: ann_creation
      options:
        comment: Creation date
    updated:
      type: datetime
      nullable: true
      column: ann_update
      options:
        comment: Update date
  lifecycleCallbacks:
    prePersist: [setCreatedValue]
    preUpdate: [setUpdatedValue]
  oneToMany:
    votes:
      targetEntity: AppBundle\Entity\Vote
      mappedBy: annuaire
  oneToOne:
    validation:
      targetEntity: AppBundle\Entity\Validation
      joinColumn:
        name: validation_id
        referencedColumnName: val_id
  manyToOne:
    owner:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      inversedBy: ownedAnnuaires
      joinColumns:
        owner_id:
          referencedColumnName: id
  manyToMany:
    sites:
      targetEntity: AppBundle\Entity\Site
      mappedBy: annuaires
