AppBundle\Entity\Annuaire:
  type: entity
  table: te_annuaire_ann
  id:
    id:
      type: integer
      column: ann_id
      generator:
        strategy: AUTO
      options:
        unsigned: true
        comment: Identifiant de l annuaire
  gedmo:
    loggable:
      loggable: true
  fields:
    name:
      type: string
      length: 64
      nullable: false
      column: ann_libelle
      options:
        comment: Nom de l annuaire
      gedmo:
        - versioned
    description:
      type: text
      length: 16777215
      nullable: true
      column: ann_description
      options:
        comment: Description de l annuaire
      gedmo:
        - versioned
    url:
      type: string
      length: 255
      nullable: true
      column: ann_url
      options:
        comment: Url officiel du site diffusant l annuaire
      gedmo:
        - versioned
    created:
      type: datetime
      nullable: false
      column: ann_creation
      options:
        comment: Creation date
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      nullable: true
      column: ann_update
      options:
        comment: Update date
      gedmo:
        timestampable:
          on: update
    ipCreator:
      type: string
      length: 45
      nullable: false
      column: sit_created_ip
      options:
        comment: IP de creation
      gedmo:
        ipTraceable:
          on: create
    ipUpdater:
      type: string
      length: 45
      nullable: false
      column: sit_updated_ip
      options:
        comment: IP de modification
      gedmo:
        ipTraceable:
          on: update
    slugUrl:
      type: string
      length: 128
      gedmo:
        slug:
          style: camel
          fields:
            - url
    slugName:
      type: string
      length: 128
      gedmo:
        slug:
          style: camel
          fields:
            - name
  oneToMany:
    votes:
      targetEntity: AppBundle\Entity\Vote
      mappedBy: annuaire
  oneToOne:
    validation:
      targetEntity: AppBundle\Entity\Validation
      joinColumn:
        name: validation_id
        referencedColumnName: val_id
  manyToOne:
    owner:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      inversedBy: ownedAnnuaires
      joinColumns:
        owner_id:
          referencedColumnName: id
  manyToMany:
    sites:
      targetEntity: AppBundle\Entity\Site
      mappedBy: annuaires
    tags:
      targetEntity: Application\Sonata\ClassificationBundle\Entity\Tag
      inversedBy: annuaires
      joinTable:
        name: tj_annuaire_tag_ata
        joinColumns:
          site_id:
            referencedColumnName: ann_id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
