AppBundle\Entity\Classement:
  type: entity
  table: te_classement_te
  id:
    id:
      type: integer
      column: cla_id
      generator:
        strategy: AUTO
      options:
        unsigned: true
        comment: Identifiant du classement
  fields:
    name:
      type: string
      length: 64
      nullable: false
      column: cla_libelle
      options:
        comment: Classement du site
    description:
      type: text
      length: 16777215
      nullable: true
      column: cla_description
      options:
        comment: Description du classement
    reason:
      type: text
      length: 65535
      nullable: true
      column: sit_raison
      options:
        comment: Explication de la décision
    status:
      type: smallint
      nullable: false
      column: cla_statut
      options:
        default: 2
        comment: Statut du classement (refusé, en attente, accepté)
    url:
      type: string
      length: 255
      nullable: true
      column: cla_url
      options:
        comment: Url officiel du site diffusant le classement
    created:
      type: datetime
      nullable: false
      column: cla_creation
      options:
        comment: Creation date
    updated:
      type: datetime
      nullable: true
      column: cla_update
      options:
        comment: Update date
    validated:
      type: datetime
      nullable: true
      column: cla_validation
      options:
        comment: Date de validation du topsite
  lifecycleCallbacks:
    prePersist: [setCreatedValue]
    preUpdate: [setUpdatedValue]
  oneToMany:
    votes:
      targetEntity: AppBundle\Entity\Vote
      mappedBy: classement
  manyToOne:
    owner:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      inversedBy: ownedClassements
      joinColumns:
        owner_id:
          referencedColumnName: id
    validator:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      inversedBy: validatedClassements
      joinColumns:
        validator_id:
          referencedColumnName: id
  manyToMany:
    sites:
      targetEntity: AppBundle\Entity\Site
      mappedBy: classements
  indexes:
    i1_classement:
      columns: [cla_statut, cla_creation]
    i2_classement:
      columns: [owner_id, cla_creation]
    i3_classement:
      columns: [validator_id, cla_creation]
