AppBundle\Entity\Site:
  type: entity
  table: te_site_sit
  gedmo:
    loggable:
      loggable: true
  id:
    id:
      type: integer
      column: sit_id
      generator:
        strategy: AUTO
      options:
        unsigned: true
        comment: Identifiant du site
  fields:
    name:
      type: string
      length: 64
      nullable: true
      column: sit_libelle
      options:
        comment: Titre du site
      gedmo:
        - versioned
    description:
      type: text
      length: 16777215
      nullable: true
      column: sit_description
      options:
        comment: Description du site
      gedmo:
        - versioned
    url:
      type: string
      unique: true
      length: 255
      nullable: true
      column: sit_url
      options:
        comment: Url officiel du site
      gedmo:
        - versioned
    ipCreator:
      type: string
      length: 45
      nullable: false
      column: sit_created_ip
      options:
        comment: IP de creation
      gedmo:
        ipTraceable:
          on: create
    ipUpdater:
      type: string
      length: 45
      nullable: false
      column: sit_updated_ip
      options:
        comment: IP de modification
      gedmo:
        ipTraceable:
          on: update
    created:
      type: datetime
      nullable: false
      column: new_creation
      options:
        comment: Creation date
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      nullable: true
      column: new_update
      options:
        comment: Update date
      gedmo:
        timestampable:
          on: update
  indexes:
    i1_site:
      columns: [sit_libelle]
  oneToOne:
    validation:
      targetEntity: AppBundle\Entity\Validation
      joinColumn:
        name: validation_id
        referencedColumnName: val_id
  oneToMany:
    votes:
      targetEntity: AppBundle\Entity\Vote
      mappedBy: site
  manyToOne:
    owner:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      inversedBy: ownedSites
      joinColumns:
        owner_id:
          referencedColumnName: id
  manyToMany:
    annuaires:
      targetEntity: AppBundle\Entity\Annuaire
      inversedBy: sites
      joinTable:
        name: tj_annuaire_site_ans
        joinColumns:
          site_id:
            referencedColumnName: sit_id
        inverseJoinColumns:
          annuaire_id:
            referencedColumnName: ann_id
    tags:
      targetEntity: Application\Sonata\ClassificationBundle\Entity\Tag
      inversedBy: sites
      joinTable:
        name: tj_site_tag_sta
        joinColumns:
          site_id:
            referencedColumnName: sit_id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
