AppBundle\Entity\Validation:
  type: entity
  table: te_validation_val
  id:
    id:
      type: integer
      column: val_id
      generator:
        strategy: AUTO
      options:
        unsigned: true
        comment: Identifiant de la validation
  fields:
    reason:
      type: text
      length: 65535
      nullable: true
      column: sit_raison
      options:
        comment: Explication de la décision
    status:
      type: smallint
      nullable: false
      column: val_status
      options:
        default: 2
        comment: Statut de l entité validée (refusé, en attente, accepté)
    created:
      type: datetime
      nullable: false
      column: val_creation
      options:
        comment: Creation date
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      nullable: true
      column: val_update
      options:
        comment: Update date
      gedmo:
        timestampable:
          on: update
  manyToOne:
    validator:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      joinColumns:
        validator_id:
          referencedColumnName: id
