AppBundle\Entity\Vote:
  type: entity
  table: te_vote_vot
  id:
    id:
      type: bigint
      column: vot_id
      generator:
        strategy: AUTO
      options:
        unsigned: true
        comment: Identifiant du classement
  fields:
    created:
      type: datetime
      nullable: false
      column: vot_creation
      options:
        comment: Creation date
      gedmo:
        timestampable:
          on: create
    ipCreator:
      type: string
      length: 45
      nullable: true
      column: vot_ip_creator
      options:
        comment: IP du voteur
      gedmo:
        ipTraceable:
          on: create
    ipUpdater:
      type: string
      length: 45
      nullable: true
      column: vot_ip_updater
      options:
        comment: IP du voteur en cas de modification
      gedmo:
        ipTraceable:
          on: update
    tracker:
      type: guid
      nullable: false
      column: vot_tracker
      options:
        comment: Tracker GGUID du voteur
    point:
      type: smallint
      nullable: false
      column: vot_point
      options:
        comment: Nombre de point que rapporte ce vote
  manyToOne:
    user:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      inversedBy: votes
      joinColumns:
        user_id:
          referencedColumnName: id
    site:
      targetEntity: AppBundle\Entity\Site
      inversedBy: votes
      joinColumns:
        site_id:
          referencedColumnName: sit_id
    annuaire:
      targetEntity: AppBundle\Entity\Annuaire
      inversedBy: votes
      joinColumns:
        annuaire_id:
          referencedColumnName: ann_id
  indexes:
    i1_vote:
      columns: [vot_creation,annuaire_id,site_id]
    i2_vote:
      columns: [user_id,site_id,vot_creation]
    i3_vote:
      columns: [vot_ip_creator,vot_creation]
