<?php
/**
 * This file is part of the PokeMe Application.
 *
 * PHP version 5
 *
 * (c) Alexandre Tranchant <alexandre.tranchant@gmail.com>
 *
 * @category Entity
 *
 * @author    Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @copyright 2015 Alexandre Tranchant
 * @license   GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */
namespace Application\Sonata\ClassificationBundle\Entity;

use AppBundle\Entity\Annuaire;
use AppBundle\Entity\Site;
use Doctrine\Common\Collections\ArrayCollection;
use Sonata\ClassificationBundle\Entity\BaseTag as BaseTag;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends ).
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @category Entity
 *
 * @author  Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @license GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */
class Tag extends BaseTag
{
    /**
     * Id.
     *
     * @var int
     */
    protected $id;

    /**
     * @var ArrayCollection
     */
    private $annuaires;

    /**
     * @var ArrayCollection
     */
    private $sites;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->sites = new ArrayCollection();
        $this->annuaires = new ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add annuaire.
     *
     * @param Annuaire $annuaire
     *
     * @return Tag
     */
    public function addAnnuaire(Annuaire $annuaire)
    {
        $this->annuaires[] = $annuaire;

        return $this;
    }

    /**
     * Remove annuaire.
     *
     * @param Annuaire $annuaire
     */
    public function removeAnnuaire(Annuaire $annuaire)
    {
        $this->annuaires->removeElement($annuaire);
    }

    /**
     * Get annuaires.
     *
     * @return ArrayCollection
     */
    public function getAnnuaires()
    {
        return $this->annuaires;
    }

    /**
     * Add site.
     *
     * @param Site $site
     *
     * @return Tag
     */
    public function addSite(Site $site)
    {
        $this->sites[] = $site;

        return $this;
    }

    /**
     * Remove site.
     *
     * @param Site $site
     */
    public function removeSite(Site $site)
    {
        $this->sites->removeElement($site);
    }

    /**
     * Get sites.
     *
     * @return ArrayCollection
     */
    public function getSites()
    {
        return $this->sites;
    }
}
