<?php
/**
 * This file is part of the PokeMe Application.
 *
 * (c) Alexandre Tranchant <alexandre.tranchant@gmail.com>
 *
 * @author      Alexandre Tranchant
 * @copyright   2015 Alexandre Tranchant
 * @license     GNU General Public License, version 3
 * @license     http://opensource.org/licenses/GPL-3.0
 */
namespace Application\Sonata\UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends ).
 *
 * References :
 *   bundles : http://symfony.com/doc/current/book/bundles.html
 *
 *
 * @category Bundle
 *
 * @author  Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @license GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */
class ApplicationSonataUserBundle extends Bundle
{
    /**
     * Return the parent name.
     *
     * @return string
     */
    public function getParent()
    {
        return 'SonataUserBundle';
    }
}
